# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        matheo_userbundle:
            entity: { class: MatheoUserBundle:User }

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:       matheo_userbundle
                csrf_provider:  form.csrf_provider
                login_path:     fos_user_security_login
                check_path:     fos_user_security_check
                default_target_path: /
                use_referer:    true
            logout:
                invalidate_session: true
                path:           fos_user_security_logout
                target:         /
            anonymous:    true

    access_control:
        - { path: ^/admin*, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }